const basicGraph = {
  groups: [
    {
      id: 1,
      label: 'Odd',
      color: '#aaffc3',
    },
    {
      id: 2,
      label: 'Even',
      color: '#f032e6',
    },
  ],
  nodes: [
    {
      id: 1,
      groupId: 1,
      label: '1',
      title: 'One',
      details: '**bold**',
      level: 1,
    },
    {
      id: 2,
      groupId: 2,
      label: '2',
      title: 'Two',
      details: 'Two  \n lines',
      level: 1,
    },
    {
      id: 3,
      groupId: 1,
      label: '3',
      title: 'Three',
      details: '_italic_',
      level: 2,
    },
    {
      id: 4,
      groupId: 2,
      label: '4',
      title: 'Four',
      details: '_italic_',
      level: 3,
    },
    {
      id: 5,
      groupId: 1,
      label: '5',
      title: 'Five',
      details: '- List item 1  \n- List item 2',
      level: 3,
    },
    {
      id: 6,
      groupId: 2,
      label: '6',
      title: 'Six',
      details: 'Sex\'s details',
      level: 4,
    },
  ],
  edges: [
    {
      id: 1,
      from: 1,
      to: 3,
      title: 'From 1 to 3',
      details: 'Edge\'s details',
    },
    {
      id: 2,
      from: 2,
      to: 3,
      title: 'From 2 to 3',
      details: 'Edge\'s details',
    },
    {
      id: 3,
      from: 3,
      to: 4,
      title: 'From 3 to 4',
      details: 'Edge\'s details',
    },
    {
      id: 4,
      from: 3,
      to: 5,
      title: 'From 3 to 5',
      details: 'Edge\'s details',
    },
    {
      id: 5,
      from: 5,
      to: 4,
      title: 'From 5 to 4',
      details: 'Edge\'s details',
    },
    {
      id: 6,
      from: 4,
      to: 6,
      title: 'From 4 to 6',
      details: 'Edge\'s details',
    },
  ],
};

export default basicGraph;
