const systemEngineerGraph = {
  nodes: [
    {
      id: 0,
      label: 'DCC203',
      title: 'PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE I',
      details: 'DCC203 - PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE I',
      level: 1,
    },
    {
      id: 1,
      label: 'ELE629',
      title: 'INTRODUÇÃO A ENGENHARIA DE SISTEMAS',
      details: 'ELE629 - INTRODUÇÃO A ENGENHARIA DE SISTEMAS',
      level: 1,
    },
    {
      id: 2,
      label: 'MAT001',
      title: 'CALCULO DIFERENCIAL E INTEGRAL I',
      details: 'MAT001 - CALCULO DIFERENCIAL E INTEGRAL I',
      level: 1,
    },
    {
      id: 3,
      label: 'MAT038',
      title: 'GEOMETRIA ANALITICA E ALGEBRA LINEAR',
      details: 'MAT038 - GEOMETRIA ANALITICA E ALGEBRA LINEAR',
      level: 1,
    },
    {
      id: 4,
      label: 'DCC033',
      title: 'ANALISE NUMERICA',
      details: 'DCC033 - ANALISE NUMERICA',
      level: 2,
    },
    {
      id: 5,
      label: 'DCC204',
      title: 'PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE II',
      details: 'DCC204 - PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE II',
      level: 2,
    },
    {
      id: 6,
      label: 'ELT124',
      title: 'SISTEMAS DIGITAIS',
      details: 'ELT124 - SISTEMAS DIGITAIS',
      level: 2,
    },
    {
      id: 7,
      label: 'FIS065',
      title: 'FUNDAMENTOS DE MECANICA',
      details: 'FIS065 - FUNDAMENTOS DE MECANICA',
      level: 2,
    },
    {
      id: 8,
      label: 'MAT039',
      title: 'CALCULO DIFERENCIAL E INTEGRAL II',
      details: 'MAT039 - CALCULO DIFERENCIAL E INTEGRAL II',
      level: 2,
    },
    {
      id: 9,
      label: 'ELE064',
      title: 'ANALISE DE CIRCUITOS ELETRICOS I',
      details: 'ELE064 - ANALISE DE CIRCUITOS ELETRICOS I',
      level: 3,
    },
    {
      id: 10,
      label: 'ELE078',
      title: 'PROGRAMACAO ORIENTADA A OBJETOS',
      details: 'ELE078 - PROGRAMACAO ORIENTADA A OBJETOS',
      level: 3,
    },
    {
      id: 11,
      label: 'FIS069',
      title: 'FUNDAMENTOS DE ELETROMAGNETISMO',
      details: 'FIS069 - FUNDAMENTOS DE ELETROMAGNETISMO',
      level: 3,
    },
    {
      id: 12,
      label: 'FIS152',
      title: 'FUNDAMENTOS DE MECÂNICA DOS FLUIDOS E TERMODINÂMICA',
      details: 'FIS152 - FUNDAMENTOS DE MECÂNICA DOS FLUIDOS E TERMODINÂMICA',
      level: 3,
    },
    {
      id: 13,
      label: 'MAT002',
      title: 'CALCULO DIFERENCIAL E INTEGRAL III',
      details: 'MAT002 - CALCULO DIFERENCIAL E INTEGRAL III',
      level: 3,
    },
    {
      id: 14,
      label: 'MAT015',
      title: 'EQUACOES DIFERENCIAIS A',
      details: 'MAT015 - EQUACOES DIFERENCIAIS A',
      level: 3,
    },
    {
      id: 15,
      label: 'DCC205',
      title: 'ESTRUTURAS DE DADOS',
      details: 'DCC205 - ESTRUTURAS DE DADOS',
      level: 4,
    },
    {
      id: 16,
      label: 'ELE065',
      title: 'ANALISE DE CIRCUITOS ELETRICOS II',
      details: 'ELE065 - ANALISE DE CIRCUITOS ELETRICOS II',
      level: 4,
    },
    {
      id: 17,
      label: 'ELT029',
      title: 'LABORATORIO DE SISTEMAS DIGITAIS',
      details: 'ELT029 - LABORATORIO DE SISTEMAS DIGITAIS',
      level: 4,
    },
    {
      id: 18,
      label: 'EST031',
      title: 'ESTATISTICA E PROBABILIDADES',
      details: 'EST031 - ESTATISTICA E PROBABILIDADES',
      level: 4,
    },
    {
      id: 19,
      label: 'FIS086',
      title: 'FUNDAMENTOS DE OSCILACOES,ONDAS E OPTICA',
      details: 'FIS086 - FUNDAMENTOS DE OSCILACOES,ONDAS E OPTICA',
      level: 4,
    },
    {
      id: 20,
      label: 'MAT016',
      title: 'EQUACOES DIFERENCIAIS B',
      details: 'MAT016 - EQUACOES DIFERENCIAIS B',
      level: 4,
    },
    {
      id: 21,
      label: 'ELE079',
      title: 'ELETROMAGNETISMO COMPUTACIONAL',
      details: 'ELE079 - ELETROMAGNETISMO COMPUTACIONAL',
      level: 5,
    },
    {
      id: 22,
      label: 'ELE092',
      title: 'LABORATORIO DE PROJETO I',
      details: 'ELE092 - LABORATORIO DE PROJETO I',
      level: 5,
    },
    {
      id: 23,
      label: 'ELT075',
      title: 'REDES NEURAIS ARTIFICIAIS',
      details: 'ELT075 - REDES NEURAIS ARTIFICIAIS',
      level: 5,
    },
    {
      id: 24,
      label: 'ELT123',
      title: 'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES',
      details: 'ELT123 - ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES',
      level: 5,
    },
    {
      id: 25,
      label: 'ELT125',
      title: 'ANÁLISE DE SISTEMAS DINÂMICOS LINEARES',
      details: 'ELT125 - ANÁLISE DE SISTEMAS DINÂMICOS LINEARES',
      level: 5,
    },
    {
      id: 26,
      label: 'EMA255',
      title: 'FLUIDOS E TERMODINAMICA COMPUTACIONAL',
      details: 'EMA255 - FLUIDOS E TERMODINAMICA COMPUTACIONAL',
      level: 5,
    },
    {
      id: 27,
      label: 'ELE080',
      title: 'ENGENHARIA DE SOFTWARE',
      details: 'ELE080 - ENGENHARIA DE SOFTWARE',
      level: 6,
    },
    {
      id: 28,
      label: 'ELE081',
      title: 'LABORATORIO DE PROJETO II',
      details: 'ELE081 - LABORATORIO DE PROJETO II',
      level: 6,
    },
    {
      id: 29,
      label: 'ELE082',
      title: 'PESQUISA OPERACIONAL',
      details: 'ELE082 - PESQUISA OPERACIONAL',
      level: 6,
    },
    {
      id: 30,
      label: 'ELE156',
      title: 'LAB.DE CIRCUITOS ELETRICOS ELETRONICA C',
      details: 'ELE156 - LAB.DE CIRCUITOS ELETRICOS ELETRONICA C',
      level: 6,
    },
    {
      id: 31,
      label: 'ELT126',
      title: 'ENGENHARIA DE CONTROLE',
      details: 'ELT126 - ENGENHARIA DE CONTROLE',
      level: 6,
    },
    {
      id: 32,
      label: 'DCC023',
      title: 'REDES DE COMPUTADORES',
      details: 'DCC023 - REDES DE COMPUTADORES',
      level: 7,
    },
    {
      id: 33,
      label: 'EEE017',
      title: 'CONFIABILIDADE DE SISTEMAS',
      details: 'EEE017 - CONFIABILIDADE DE SISTEMAS',
      level: 7,
    },
    {
      id: 34,
      label: 'ELE077',
      title: 'OTIMIZACAO NAO LINEAR',
      details: 'ELE077 - OTIMIZACAO NAO LINEAR',
      level: 7,
    },
    {
      id: 35,
      label: 'ELE084',
      title: 'LABORATORIO DE PROJETO III',
      details: 'ELE084 - LABORATORIO DE PROJETO III',
      level: 7,
    },
    {
      id: 36,
      label: 'ELT079',
      title: 'DISPOSIT.E CIRCUITOS ELETRONICOS BASICOS',
      details: 'ELT079 - DISPOSIT.E CIRCUITOS ELETRONICOS BASICOS',
      level: 7,
    },
    {
      id: 37,
      label: 'ELE042',
      title: 'PROCESSAMENTOS DE SINAIS',
      details: 'ELE042 - PROCESSAMENTOS DE SINAIS',
      level: 8,
    },
    {
      id: 38,
      label: 'ELE075',
      title: 'SISTEMAS NEBULOSOS',
      details: 'ELE075 - SISTEMAS NEBULOSOS',
      level: 8,
    },
    {
      id: 39,
      label: 'ELE083',
      title: 'COMPUTACAO EVOLUCIONARIA',
      details: 'ELE083 - COMPUTACAO EVOLUCIONARIA',
      level: 8,
    },
    {
      id: 40,
      label: 'ELE086',
      title: 'LABORATORIO DE PROJETO IV',
      details: 'ELE086 - LABORATORIO DE PROJETO IV',
      level: 8,
    },
    {
      id: 41,
      label: 'ELE088',
      title: 'TEORIA DA DECISAO',
      details: 'ELE088 - TEORIA DA DECISAO',
      level: 8,
    },
    {
      id: 42,
      label: 'ELT016',
      title: 'TECNICAS DE MODELAGEM DE SIST. DINAMICOS',
      details: 'ELT016 - TECNICAS DE MODELAGEM DE SIST. DINAMICOS',
      level: 8,
    },
    {
      id: 43,
      label: 'ELT080',
      title: 'LAB.DE CIRCUITOS ELETRONICOS E PROJETOS',
      details: 'ELT080 - LAB.DE CIRCUITOS ELETRONICOS E PROJETOS',
      level: 8,
    },
    {
      id: 44,
      label: 'ELE087',
      title: 'PROJETO MULTIDISCIPLINAR',
      details: 'ELE087 - PROJETO MULTIDISCIPLINAR',
      level: 9,
    },
    {
      id: 45,
      label: 'ELE094',
      title: 'LABORATORIO DE PROJETO V',
      details: 'ELE094 - LABORATORIO DE PROJETO V',
      level: 9,
    },
    {
      id: 46,
      label: 'EEE018',
      title: 'TRABALHO DE CONCLUSAO DE CURSO I',
      details: 'ELE018 - TRABALHO DE CONCLUSAO DE CURSO I',
      level: 10,
    },
    {
      id: 47,
      label: 'EEE019',
      title: 'TRABALHO DE CONCLUSAO DE CURSO II',
      details: 'ELE019 - TRABALHO DE CONCLUSAO DE CURSO II',
      level: 11,
    },
    {
      id: 48,
      label: 'EEE020',
      title: 'EEE020',
      details: 'EEE020',
      level: 12,
    },
  ],
  edges: [
    {
      id: 0,
      from: 0,
      to: 4,
    },
    {
      id: 1,
      from: 3,
      to: 4,
    },
    {
      id: 2,
      from: 0,
      to: 5,
    },
    {
      id: 3,
      from: 2,
      to: 8,
    },
    {
      id: 4,
      from: 3,
      to: 8,
    },
    {
      id: 5,
      from: 5,
      to: 10,
    },
    {
      id: 6,
      from: 7,
      to: 11,
    },
    {
      id: 7,
      from: 8,
      to: 11,
    },
    {
      id: 8,
      from: 7,
      to: 12,
    },
    {
      id: 9,
      from: 2,
      to: 12,
    },
    {
      id: 10,
      from: 8,
      to: 13,
    },
    {
      id: 11,
      from: 8,
      to: 14,
    },
    {
      id: 12,
      from: 5,
      to: 15,
    },
    {
      id: 13,
      from: 9,
      to: 16,
    },
    {
      id: 14,
      from: 14,
      to: 16,
    },
    {
      id: 15,
      from: 6,
      to: 17,
    },
    {
      id: 16,
      from: 11,
      to: 19,
    },
    {
      id: 17,
      from: 8,
      to: 20,
    },
    {
      id: 18,
      from: 11,
      to: 21,
    },
    {
      id: 19,
      from: 5,
      to: 23,
    },
    {
      id: 20,
      from: 14,
      to: 23,
    },
    {
      id: 21,
      from: 18,
      to: 23,
    },
    {
      id: 22,
      from: 14,
      to: 25,
    },
    {
      id: 23,
      from: 12,
      to: 26,
    },
    {
      id: 24,
      from: 10,
      to: 27,
    },
    {
      id: 25,
      from: 22,
      to: 28,
    },
    {
      id: 26,
      from: 14,
      to: 29,
    },
    {
      id: 27,
      from: 16,
      to: 30,
    },
    {
      id: 28,
      from: 25,
      to: 31,
    },
    {
      id: 29,
      from: 5,
      to: 32,
    },
    {
      id: 30,
      from: 18,
      to: 33,
    },
    {
      id: 31,
      from: 4,
      to: 34,
    },
    {
      id: 32,
      from: 14,
      to: 34,
    },
    {
      id: 33,
      from: 28,
      to: 35,
    },
    {
      id: 34,
      from: 25,
      to: 37,
    },
    {
      id: 35,
      from: 14,
      to: 38,
    },
    {
      id: 36,
      from: 34,
      to: 39,
    },
    {
      id: 37,
      from: 35,
      to: 40,
    },
    {
      id: 38,
      from: 34,
      to: 41,
    },
    {
      id: 39,
      from: 25,
      to: 42,
    },
    {
      id: 40,
      from: 36,
      to: 43,
    },
    {
      id: 41,
      from: 40,
      to: 44,
    },
    {
      id: 42,
      from: 46,
      to: 47,
    },
  ],
};

export default systemEngineerGraph;
