const systemEngineerGraph = {
  nodes: [
    {
      id: 0,
      label: 'DCC203',
      title: 'DCC203',
      details: 'DCC203',
      level: 1,
    },
    {
      id: 1,
      label: 'ELE629',
      title: 'ELE629',
      details: 'ELE629',
      level: 1,
    },
    {
      id: 2,
      label: 'MAT001',
      title: 'MAT001',
      details: 'MAT001',
      level: 1,
    },
    {
      id: 3,
      label: 'MAT038',
      title: 'MAT038',
      details: 'MAT038',
      level: 1,
    },
    {
      id: 4,
      label: 'DCC033',
      title: 'DCC033',
      details: 'DCC033',
      level: 2,
    },
    {
      id: 5,
      label: 'DCC204',
      title: 'DCC204',
      details: 'DCC204',
      level: 2,
    },
    {
      id: 6,
      label: 'ELT124',
      title: 'ELT124',
      details: 'ELT124',
      level: 2,
    },
    {
      id: 7,
      label: 'FIS065',
      title: 'FIS065',
      details: 'FIS065',
      level: 2,
    },
    {
      id: 8,
      label: 'MAT039',
      title: 'MAT039',
      details: 'MAT039',
      level: 2,
    },
    {
      id: 9,
      label: 'ELE064',
      title: 'ELE064',
      details: 'ELE064',
      level: 3,
    },
    {
      id: 10,
      label: 'ELE078',
      title: 'ELE078',
      details: 'ELE078',
      level: 3,
    },
    {
      id: 11,
      label: 'FIS069',
      title: 'FIS069',
      details: 'FIS069',
      level: 3,
    },
    {
      id: 12,
      label: 'FIS152',
      title: 'FIS152',
      details: 'FIS152',
      level: 3,
    },
    {
      id: 13,
      label: 'MAT002',
      title: 'MAT002',
      details: 'MAT002',
      level: 3,
    },
    {
      id: 14,
      label: 'MAT015',
      title: 'MAT015',
      details: 'MAT015',
      level: 3,
    },
    {
      id: 15,
      label: 'DCC205',
      title: 'DCC205',
      details: 'DCC205',
      level: 4,
    },
    {
      id: 16,
      label: 'ELE065',
      title: 'ELE065',
      details: 'ELE065',
      level: 4,
    },
    {
      id: 17,
      label: 'ELT029',
      title: 'ELT029',
      details: 'ELT029',
      level: 4,
    },
    {
      id: 18,
      label: 'EST031',
      title: 'EST031',
      details: 'EST031',
      level: 4,
    },
    {
      id: 19,
      label: 'FIS086',
      title: 'FIS086',
      details: 'FIS086',
      level: 4,
    },
    {
      id: 20,
      label: 'MAT016',
      title: 'MAT016',
      details: 'MAT016',
      level: 4,
    },
    {
      id: 21,
      label: 'ELE079',
      title: 'ELE079',
      details: 'ELE079',
      level: 5,
    },
    {
      id: 22,
      label: 'ELE092',
      title: 'ELE092',
      details: 'ELE092',
      level: 5,
    },
    {
      id: 23,
      label: 'ELT075',
      title: 'ELT075',
      details: 'ELT075',
      level: 5,
    },
    {
      id: 24,
      label: 'ELT123',
      title: 'ELT123',
      details: 'ELT123',
      level: 5,
    },
    {
      id: 25,
      label: 'ELT125',
      title: 'ELT125',
      details: 'ELT125',
      level: 5,
    },
    {
      id: 26,
      label: 'EMA255',
      title: 'EMA255',
      details: 'EMA255',
      level: 5,
    },
    {
      id: 27,
      label: 'ELE080',
      title: 'ELE080',
      details: 'ELE080',
      level: 6,
    },
    {
      id: 28,
      label: 'ELE081',
      title: 'ELE081',
      details: 'ELE081',
      level: 6,
    },
    {
      id: 29,
      label: 'ELE082',
      title: 'ELE082',
      details: 'ELE082',
      level: 6,
    },
    {
      id: 30,
      label: 'ELE156',
      title: 'ELE156',
      details: 'ELE156',
      level: 6,
    },
    {
      id: 31,
      label: 'ELT126',
      title: 'ELT126',
      details: 'ELT126',
      level: 6,
    },
    {
      id: 32,
      label: 'DCC023',
      title: 'DCC023',
      details: 'DCC023',
      level: 7,
    },
    {
      id: 33,
      label: 'EEE017',
      title: 'EEE017',
      details: 'EEE017',
      level: 7,
    },
    {
      id: 34,
      label: 'ELE077',
      title: 'ELE077',
      details: 'ELE077',
      level: 7,
    },
    {
      id: 35,
      label: 'ELE084',
      title: 'ELE084',
      details: 'ELE084',
      level: 7,
    },
    {
      id: 36,
      label: 'ELT079',
      title: 'ELT079',
      details: 'ELT079',
      level: 7,
    },
    {
      id: 37,
      label: 'ELE042',
      title: 'ELE042',
      details: 'ELE042',
      level: 8,
    },
    {
      id: 38,
      label: 'ELE075',
      title: 'ELE075',
      details: 'ELE075',
      level: 8,
    },
    {
      id: 39,
      label: 'ELE083',
      title: 'ELE083',
      details: 'ELE083',
      level: 8,
    },
    {
      id: 40,
      label: 'ELE086',
      title: 'ELE086',
      details: 'ELE086',
      level: 8,
    },
    {
      id: 41,
      label: 'ELE088',
      title: 'ELE088',
      details: 'ELE088',
      level: 8,
    },
    {
      id: 42,
      label: 'ELT016',
      title: 'ELT016',
      details: 'ELT016',
      level: 8,
    },
    {
      id: 43,
      label: 'ELT080',
      title: 'ELT080',
      details: 'ELT080',
      level: 8,
    },
    {
      id: 44,
      label: 'ELE087',
      title: 'ELE087',
      details: 'ELE087',
      level: 9,
    },
    {
      id: 45,
      label: 'ELE094',
      title: 'ELE094',
      details: 'ELE094',
      level: 9,
    },
    {
      id: 46,
      label: 'EEE018',
      title: 'EEE018',
      details: 'EEE018',
      level: 10,
    },
    {
      id: 47,
      label: 'EEE019',
      title: 'EEE019',
      details: 'EEE019',
      level: 11,
    },
    {
      id: 48,
      label: 'EEE020',
      title: 'EEE020',
      details: 'EEE020',
      level: 12,
    },
  ],
  edges: [
    {
      id: 0,
      from: 0,
      to: 4,
      arrows: 'to',
    },
    {
      id: 1,
      from: 3,
      to: 4,
      arrows: 'to',
    },
    {
      id: 2,
      from: 0,
      to: 5,
      arrows: 'to',
    },
    {
      id: 3,
      from: 2,
      to: 8,
      arrows: 'to',
    },
    {
      id: 4,
      from: 3,
      to: 8,
      arrows: 'to',
    },
    {
      id: 5,
      from: 5,
      to: 10,
      arrows: 'to',
    },
    {
      id: 6,
      from: 7,
      to: 11,
      arrows: 'to',
    },
    {
      id: 7,
      from: 8,
      to: 11,
      arrows: 'to',
    },
    {
      id: 8,
      from: 7,
      to: 12,
      arrows: 'to',
    },
    {
      id: 9,
      from: 2,
      to: 12,
      arrows: 'to',
    },
    {
      id: 10,
      from: 8,
      to: 13,
      arrows: 'to',
    },
    {
      id: 11,
      from: 8,
      to: 14,
      arrows: 'to',
    },
    {
      id: 12,
      from: 5,
      to: 15,
      arrows: 'to',
    },
    {
      id: 13,
      from: 9,
      to: 16,
      arrows: 'to',
    },
    {
      id: 14,
      from: 14,
      to: 16,
      arrows: 'to',
    },
    {
      id: 15,
      from: 6,
      to: 17,
      arrows: 'to',
    },
    {
      id: 16,
      from: 11,
      to: 19,
      arrows: 'to',
    },
    {
      id: 17,
      from: 8,
      to: 20,
      arrows: 'to',
    },
    {
      id: 18,
      from: 11,
      to: 21,
      arrows: 'to',
    },
    {
      id: 19,
      from: 5,
      to: 23,
      arrows: 'to',
    },
    {
      id: 20,
      from: 14,
      to: 23,
      arrows: 'to',
    },
    {
      id: 21,
      from: 18,
      to: 23,
      arrows: 'to',
    },
    {
      id: 22,
      from: 14,
      to: 25,
      arrows: 'to',
    },
    {
      id: 23,
      from: 12,
      to: 26,
      arrows: 'to',
    },
    {
      id: 24,
      from: 10,
      to: 27,
      arrows: 'to',
    },
    {
      id: 25,
      from: 22,
      to: 28,
      arrows: 'to',
    },
    {
      id: 26,
      from: 14,
      to: 29,
      arrows: 'to',
    },
    {
      id: 27,
      from: 16,
      to: 30,
      arrows: 'to',
    },
    {
      id: 28,
      from: 25,
      to: 31,
      arrows: 'to',
    },
    {
      id: 29,
      from: 5,
      to: 32,
      arrows: 'to',
    },
    {
      id: 30,
      from: 18,
      to: 33,
      arrows: 'to',
    },
    {
      id: 31,
      from: 4,
      to: 34,
      arrows: 'to',
    },
    {
      id: 32,
      from: 14,
      to: 34,
      arrows: 'to',
    },
    {
      id: 33,
      from: 28,
      to: 35,
      arrows: 'to',
    },
    {
      id: 34,
      from: 25,
      to: 37,
      arrows: 'to',
    },
    {
      id: 35,
      from: 14,
      to: 38,
      arrows: 'to',
    },
    {
      id: 36,
      from: 34,
      to: 39,
      arrows: 'to',
    },
    {
      id: 37,
      from: 35,
      to: 40,
      arrows: 'to',
    },
    {
      id: 38,
      from: 34,
      to: 41,
      arrows: 'to',
    },
    {
      id: 39,
      from: 25,
      to: 42,
      arrows: 'to',
    },
    {
      id: 40,
      from: 36,
      to: 43,
      arrows: 'to',
    },
    {
      id: 41,
      from: 40,
      to: 44,
      arrows: 'to',
    },
    {
      id: 42,
      from: 46,
      to: 47,
      arrows: 'to',
    },
    {
      id: 43,
      from: 1,
      to: 8,
      hidden: true,
    },
    {
      id: 44,
      from: 1,
      to: 6,
      hidden: true,
    },
    {
      id: 45,
      from: 17,
      to: 22,
      hidden: true,
    },
    {
      id: 46,
      from: 17,
      to: 24,
      hidden: true,
    },
    {
      id: 47,
      from: 27,
      to: 36,
      hidden: true,
    },
    {
      id: 48,
      from: 37,
      to: 45,
      hidden: true,
    },
    {
      id: 49,
      from: 45,
      to: 46,
      hidden: true,
    },
    {
      id: 50,
      from: 47,
      to: 48,
      hidden: true,
    },
  ],
};

export default systemEngineerGraph;
