const systemEngineerGraph = {
  groups: [
    {
      id: 1,
      label: 'BC-Bas Cie',
      subGroups: [
        {
          id: 1,
          label: 'BC-Mat',
        },
        {
          id: 2,
          label: 'BC-Qui',
        },
        {
          id: 3,
          label: 'BC-Alg&Prog',
        },
        {
          id: 4,
          label: 'BC-Fis',
        },
        {
          id: 5,
          label: 'BC-Est',
        },
      ],
      color: '#AC92EB',
    },
    {
      id: 2,
      label: 'PES-Prof Eng Sist',
      subGroups: [
        {
          id: 1,
          label: 'PES-Fund ES',
        },
        {
          id: 2,
          label: 'PES-ES Aplicada',
        },
        {
          id: 3,
          label: 'PES-Gestão Técnica',
        },
      ],
      color: '#4FC1E8',
    },
    {
      id: 3,
      label: 'BE-Bas Eng',
      subGroups: [
        {
          id: 1,
          label: 'BE-Eletri/on Aplic',
        },
        {
          id: 2,
          label: 'BE-Alg&Prog',
        },
        {
          id: 3,
          label: 'BE-Cie Mat',
        },
      ],
      color: '#A0D568',
    },
    {
      id: 4,
      label: 'PE-Prof Eng',
      subGroups: [
        {
          id: 1,
          label: 'PE-Eletr Anal&Dig',
        },
        {
          id: 2,
          label: 'PE-Otimiz',
        },
        {
          id: 3,
          label: 'PE-Inform',
        },
        {
          id: 4,
          label: 'PE-Mod&Simul',
        },
        {
          id: 5,
          label: 'PE-Int Comp',
        },
        {
          id: 6,
          label: 'PE-Sist Aut&Contr',
        },
      ],
      color: '#FFCE54',
    },
    {
      id: 5,
      label: 'INT-Integrador',
      subGroups: [
        {
          id: 1,
          label: 'INT-Ativ Integ',
        },
        {
          id: 2,
          label: 'INT-Estágio',
        },
        {
          id: 3,
          label: 'INT-TCC',
        },
      ],
      color: '#ED5564',
    },
  ],
  nodes: [
    {
      id: 1,
      label: 'MAT001',
      title: 'CALCULO DIFERENCIAL E INTEGRAL I',
      details: "Integrais- impróprias: seqüências séries numéricas. Funções de R em R. Derivadas. Integrais. Aplicações. \"Regras de L'Hospital\".",
      level: 1,
      weight: 90,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 2,
      label: 'MAT038',
      title: 'GEOMETRIA ANALITICA E ALGEBRA LINEAR',
      details: 'Álgebra vetorial. Retas e planos. Matrizes, sistemas lineares e determinantes. Espaço vetorial Rn. Autovalores e autovetores de matrizes. Diagonalização de matrizes simétricas.',
      level: 1,
      weight: 60,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 3,
      label: 'QUI259',
      title: 'FUNDAMENTOS DE QUIMICA PARA ENGENHARIA',
      details: 'Reações em solução aquosa e estequiometria, termoquímica, cinética química, equilíbrio químico, fundamentos de eletroquímica, ligação iônica, ligação covalente, interações intermoleculares, química aplicada a engenharia e geologia.',
      level: 1,
      weight: 60,
      groupId: 1,
      subGroupId: 2,
    },
    {
      id: 4,
      label: 'DCC203',
      title: 'PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE I',
      details: 'Introdução ao funcionamento de um computador e ao desenvolvimento de programas. Desenvolvimento de programas em uma linguagem de alto nível. Tipos de dados simples, apontadores, variáveis compostas homogêneas e heterogêneas. Entrada e saída. Estruturas de controle e repetição. Funções e ferramentas de modularização.',
      level: 1,
      weight: 60,
      groupId: 1,
      subGroupId: 3,
    },
    {
      id: 5,
      label: 'ELE629',
      title: 'INTRODUCAO A ENGENHARIA DE SISTEMAS',
      details: 'A UFMG e a Escola de Engenharia: contexto acadêmico. História da engenharia: passado, presente e futuro. O Curso de Engenharia de Sistemas da UFMG: características, grade curricular, normas e resoluções acadêmicas. Engenharia de Sistemas: pensamento sistêmico, perfil profissional, conceitos, contexto e aplicações. Preparação do aluno: organização do tempo, cuidados na elaboração e apresentação de trabalhos acadêmicos',
      level: 1,
      weight: 30,
      groupId: 2,
      subGroupId: 1,
    },
    {
      id: 6,
      label: 'FIS065',
      title: 'FUNDAMENTOS DE MECANICA',
      details: 'Cinemática e dinâmica da partícula. Sistemas de partículas. Cinemática e dinâmica de rotação. Leis de Conservação da Energia e dos Momentos Linear e Angular.',
      level: 2,
      weight: 60,
      groupId: 1,
      subGroupId: 4,
    },
    {
      id: 7,
      label: 'MAT039',
      title: 'CALCULO DIFERENCIAL E INTEGRAL II',
      details: 'Coordenadas polares. Cônicas. Séries. Série e fórmula de Taylor. Diferenciabilidade de funções de várias variáveis.',
      level: 2,
      weight: 60,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 8,
      label: 'DCC204',
      title: 'PROGRAMAÇÃO E DESENVOLVIMENTO DE SOFTWARE II',
      details: 'Programação estruturada e linguagem de programação modular. Metodologias de desenvolvimento de software. Compreensão, corretude e depuração de programas. Resolução de problemas de forma modular e eficiente.',
      level: 2,
      weight: 60,
      groupId: 1,
      subGroupId: 3,
    },
    {
      id: 9,
      label: 'ESAXXX',
      title: 'CIÊNCIAS DO AMBIENTE',
      details: 'A DEFINIR',
      level: 2,
      weight: 30,
      groupId: 3,
    },
    {
      id: 10,
      label: 'ELT124',
      title: 'SISTEMAS DIGITAIS',
      details: 'Sistemas de numeração. Álgebra Booleana. Portas lógicas. Circuitos combinacionais: análise, síntese e técnicas de minimização. Circuitos seqüenciais síncronos e assíncronos. Análise, síntese e técnicas de minimização de circuitos seqüenciais. Famílias de circuitos lógicos. Dispositivos lógicos programáveis. "Gate arrays". Análise e projeto de sistemas digitais. Fundamentos de Linguagem de Descrição de Hardware e sua aplicaçãono projeto de Sistemas Digitais.',
      level: 2,
      weight: 60,
      groupId: 4,
      subGroupId: 1,
    },
    {
      id: 11,
      label: 'ELEXXI',
      title: 'PENSAMENTO SISTÊMICO',
      details: 'Conceitos e aplicações de sistemas. Teoria de Sistemas. Pensamento Sistêmico. Teoria da Complexidade. ',
      level: 2,
      weight: 30,
      groupId: 2,
      subGroupId: 1,
    },
    {
      id: 12,
      label: 'EST031',
      title: 'ESTATISTICA E PROBABILIDADES',
      details: 'Estatística descritiva. Probabilidades. Variáveis aleatórias discretas. Variáveis aleatórias contínuas. Teorema central do limite. Estimação. Testes de hipóteses.',
      level: 3,
      weight: 60,
      groupId: 1,
      subGroupId: 5,
    },
    {
      id: 13,
      label: 'FIS069',
      title: 'FUNDAMENTOS DE ELETROMAGNETISMO',
      details: 'Carga elétrica, campo elétrico e a lei de Gauss. Potencial elétrico, capacitores e dielétricos. Corrente e resistência elétricas. Campo magnético e lei de Ampère. Lei de Faraday e indutância. Materiais magnéticos. Equações de Maxwell',
      level: 3,
      weight: 60,
      groupId: 1,
      subGroupId: 4,
    },
    {
      id: 14,
      label: 'MAT040',
      title: 'EQUACOES DIFERENCIAIS C',
      details: 'Equações Diferenciais Ordinárias de 1a e 2a Ordens. Soluções de Equações Diferenciais em Séries de Potências. Sistemas de Equações Diferenciais Lineares. Transformada de Laplace. Séries de Fourier. Equações Diferenciais Parciais. ',
      level: 3,
      weight: 60,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 15,
      label: 'DCC205',
      title: 'ESTRUTURAS DE DADOS',
      details: 'Análise de algoritmos. Abstração de dados. Introdução às técnicas de análise de algoritmos. Estruturas de dados estáticas e dinâmicas na memória principal e secundária. Estruturas de dados para realização eficiente de operações sobre dados.',
      level: 3,
      weight: 60,
      groupId: 1,
      subGroupId: 3,
    },
    {
      id: 16,
      label: 'ELE064',
      title: 'ANALISE DE CIRCUITOS ELETRICOS I',
      details: 'Fontes de tensão e corrente dependentes e independentes. Leis fundamentais de circuitos. Circuitos resistivos. Métodos de análise de circuitos. Teoremas de rede. Circuitos com amplificador operacional ideal.',
      level: 3,
      weight: 30,
      groupId: 3,
      subGroupId: 1,
    },
    {
      id: 17,
      label: 'ELT029',
      title: 'LABORATORIO DE SISTEMAS DIGITAIS',
      details: 'Aulas práticas envolvendo circuitos combinacionais, circuitos sequenciais síncronos e assíncronos e dispositivos lógicos programáveis. Gate Arrays. Análise e projeto de sistemas digitais.',
      level: 3,
      weight: 30,
      groupId: 4,
      subGroupId: 1,
    },
    {
      id: 18,
      label: 'FIS086',
      title: 'FUNDAMENTOS DE OSCILAÇÕES, ONDAS E ÓPTICA',
      details: 'Oscilações Mecânicas. Circuitos elétricos de corrente alternada. Ondas Mecânicas. Som. Ondas Eletromagnéticas. Polarização. Birrefringência. Interferência e difração da luz.',
      level: 4,
      weight: 60,
      groupId: 1,
      subGroupId: 4,
    },
    {
      id: 19,
      label: 'FIS152',
      title: 'FUNDAMENTOS DE MECÂNICA DOS FLUIDOS E TERMODINÂMICA',
      details: 'Temperatura e dilatação. Modelo cinético do gás ideal. Calor e a primeira lei da termodinâmica. Entropia e a segunda lei da termodinâmica. Estática e dinâmica de fluidos. Equação de Bernoulli.',
      level: 4,
      weight: 30,
      groupId: 1,
      subGroupId: 4,
    },
    {
      id: 20,
      label: 'MAT002',
      title: 'CALCULO DIFERENCIAL E INTEGRAL III',
      details: 'Integração de funções de duas ou mais variáveis. Integrais de linha e de superfície. Teorema de Gauss e de Stokes.',
      level: 4,
      weight: 60,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 21,
      label: 'ELEXXA',
      title: 'ANÁLISE, PROJETO E PROGRAMAÇÃO ORIENTADOS A OBJETOS',
      details: 'Gerenciamento da Complexidade; Introdução a Análise e Projeto Orientados a Objetos; Modelagem Orientada a Objetos; Implementação dos Conceitos em uma Linguagem OO; Introdução aos Padrões de Projeto OO; Introdução à Modelagem Estrutural, Comportamental e de Arquitetura.',
      level: 4,
      weight: 60,
      groupId: 3,
      subGroupId: 2,
    },
    {
      id: 22,
      label: 'ELE065',
      title: 'ANALISE DE CIRCUITOS ELETRICOS II',
      details: 'Indutância, capacitância e indutância mútua. Circuitos de primeira ordem (RC, RL e outros circuitos). Circuitos de segunda ordem (RLC série, RLC paralelo e outros circuitos). Excitação senoidal e fasores. Análise em Regime permanente senoidal. Potência em regime permanente senoidal.',
      level: 4,
      weight: 30,
      groupId: 3,
      subGroupId: 1,
    },
    {
      id: 23,
      label: 'ELE082',
      title: 'PESQUISA OPERACIONAL',
      details: 'Programação linear e suas aplicações. Método simplex. Análise de sensibilidade e dualidade. Otimização em redes. Programação dinâmica. Otimização combinatória e heurísticas. Modelagem.',
      level: 4,
      weight: 60,
      groupId: 4,
      subGroupId: 2,
    },
    {
      id: 24,
      label: 'EMAXXX',
      title: 'CIÊNCIA E TECNOLOGIA DOS MATERIAIS e PROCESSOS DE MANUFATURA',
      details: 'Importância da manufatura. Materiais na manufatura: metais, polímeros, cerâmicas e compósitos; propriedades e estrutura dos materiais; materiais mono e polifásicos. Fundição, conformação mecânica, soldagem, usinagem, injeção, sopramento, sinterização, manufatura aditiva.',
      level: 5,
      weight: 30,
      groupId: 3,
      subGroupId: 3,
    },
    {
      id: 25,
      label: 'ELEXXB',
      title: 'PROJETO DE ALGORITMOS PARA ENGENHARIA (PAE)',
      details: 'Definições e terminologia de grafos. Estruturas de dados para representação de grafos. Algoritmos elementares em grafos. Caminhos e Circuitos. Árvores e árvores geradoras mínimas. Conectividade, coloração, independência, dominância, cobertura e casamentos. Paradigmas de projeto de algoritmos: força-bruta, retrocesso, branch and bound, divisão e conquista, programação dinâmica e algoritmos gulosos. Teoria da Complexidade: classes de problemas P, NP, NP-Completo e NP-Difícil. Teorema de Cook.',
      level: 5,
      weight: 60,
      groupId: 3,
      subGroupId: 2,
    },
    {
      id: 26,
      label: 'ELE156',
      title: 'LABORATORIO DE CIRCUITOS  ELETRICOS E ELETRONICA C',
      details: 'Componentes passivos: resistores, capacitores e indutores. Circuitos RL e RC excitados por degrau. Análise de circuitos com excitação senoidal. Conceito de impedância. Definição e medidas de: valor eficaz, valor médio, potência, distorção harmônica, fator de forma, fator de potência. Análise transitória de circuitos RC, RL e RLC. Resposta em freqüência de circuitos RC, RL e RLC. Circuitos com amplificadores operacionais. Circuitos trifásicos.',
      level: 5,
      weight: 30,
      groupId: 3,
      subGroupId: 1,
    },
    {
      id: 27,
      label: 'ELT079',
      title: 'DISPOSITIVOS E CIRCUITOS ELETRONICOS BASICOS',
      details: 'Introdução à Eletrônica. Circuitos Eletrônicos com Amplificadores Operacionais ideais e reais. Junção PN. Diodos Retificadores e Zener: característica, circuitos com diodos e aplicações. Transistores de Efeito de Campo (FET) e Transistores bipolares (BJT): características, modelos, polarização, análises em pequenos sinais, resposta em frequência. Funcionamento dos transistores como chaves. Conversores A/D e D/A: conceitos básicos. Representação gráfica de circuitos eletrônicos e simulação.',
      level: 5,
      weight: 60,
      groupId: 4,
      subGroupId: 3,
    },
    {
      id: 28,
      label: 'ELT123',
      title: 'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES',
      details: 'Arquitetura de microprocessadores: unidade de controle, memória, entrada e saída. Programação de microprocessadores: tipos e formatos de instruções, modos de endereçamento, linguagens Assembly e C. Dispositivos periféricos, interrupção, acesso direto à memória. Barramentos-padrão. Ferramentas para análise, desenvolvimento e depuração. Microprocessadores comerciais. Projetos de aplicações com microprocessadores e interfaces de E/S. Multiprocessamento. ',
      level: 5,
      weight: 60,
      groupId: 4,
      subGroupId: 3,
    },
    {
      id: 29,
      label: 'ENGXXA',
      title: 'MODELAGEM E SIMULAÇÃO MULTIFÍSICA',
      details: 'Modelagem de Sistemas Físicos  usando PDEs, Transferência de Calor, Eletromagnetismo, Análise Acústica, Mecânica dos Sólidos e Fluidos.',
      level: 5,
      weight: 60,
      groupId: 4,
      subGroupId: 4,
    },
    {
      id: 30,
      label: 'ELT080',
      title: 'LABORATORIO DE CIRCUITOS ELETRONICOS E PROJETOS',
      details: 'Utilização dos equipamentos e instrumentos de Laboratório; Análise e Projetos com Amplificadores Operacionais Reais; Análise e Projeto de circuitos com Diodos retificadores e Zener; Análise e Projeto de circuitos com Transistores bipolares e MOSFET´s: como amplificador e como interruptor estático; Amplificador linear.',
      level: 6,
      weight: 30,
      groupId: 4,
      subGroupId: 1,
    },
    {
      id: 31,
      label: 'ELEXXD',
      title: 'FUNDAMENTOS DE INTELIGÊNCIA ARTIFICIAL',
      details: 'Inteligência artificial e agentes inteligentes. Arquiteturas de agentes inteligentes. Representação do conhecimento. Problema de busca em grafos. Algoritmos de busca. Heurísticas de busca. Algoritmo A*. Redes de restrições e satisfação de restrições. Proposições e inferência. Raciocínio com incertezas. Raciocínio baseado em casos. Planejamento. Planejamento com incertezas. Redes de decisão. Processos de decisão markovianos. 2/2 Introdução a sistemas multiagente. Aspectos sociais e éticos da inteligência artificial.',
      level: 6,
      weight: 30,
      groupId: 4,
      subGroupId: 5,
    },
    {
      id: 32,
      label: 'ELEXXE',
      title: 'LABORATORIO DE SISTEMAS  I',
      details: 'Engenharia de requisitos: visão geral, atividades, ferramentas e técnicas para definição, análise e gerência de requisitos. Modelagem em engenharia de sistemas. SysML.',
      level: 6,
      weight: 60,
      groupId: 2,
      subGroupId: 2,
    },
    {
      id: 33,
      label: 'ELEXXJ',
      title: 'PROCESSOS E MÉTODOS EM ENGENHARIA DE SISTEMAS',
      details: 'Modelos de ciclo de vida para sistemas.  Visão detalhada dos processos de ciclo de vida de sistemas segundo a norma ISO/IEC 15288, o INCOSE Handbook e o SEBOK. Outras normas relevantes relacionadas a software e sistemas. Demais atividades especializadas de engenharia de sistemas.',
      level: 6,
      weight: 60,
      groupId: 2,
      subGroupId: 1,
    },
    {
      id: 34,
      label: 'EEE017',
      title: 'CONFIABILIDADE DE SISTEMAS',
      details: 'Conceitos Básicos de Estatística e Probabilidade.  Engenharia de Confiabilidade: Confiabilidade, Manutenabilidade e Disponibilidade. Engenharia de Manutenção. FMEA (Modos de Falhas e Análise dos Efeitos) e FTA (Árvore de Falhas). Manutenção Centrada na Confiabilidade. Estudo de caso de um processo industrial / comercial.',
      level: 6,
      weight: 60,
      groupId: 4,
      subGroupId: 5,
    },
    {
      id: 35,
      label: 'ELE077',
      title: 'OTIMIZACAO NAO LINEAR',
      details: 'Formulação de problemas de otimização. Propriedades geométricas dos espaços de busca: convexidade, diferenciabilidade, modalidade. Condições de otimalidade. Métodos determinísticos para otimização irrestrita. Métodos sem derivadas. Métodos para otimização restrita.',
      level: 6,
      weight: 30,
      groupId: 4,
      subGroupId: 2,
    },
    {
      id: 36,
      label: 'DCC111',
      title: 'MATEMÁTICA DISCRETA',
      details: 'Estudo de fundamentos de lógica, técnicas de prova, indução matemática, teoria de conjuntos, análise combinatória, funções, recursão, relações em conjuntos e teoria dos grafos.',
      level: 7,
      weight: 60,
      groupId: 1,
      subGroupId: 1,
    },
    {
      id: 37,
      label: 'DCC011',
      title: 'INTRODUÇÃO A BANCO DE DADOS',
      details: 'Memoria auxiliar; organizacao fisica e logica. Metodos de acesso.Estruturas de arquivos. Manipulacao de bancos de dados. Linguagense pacotes. Recuperacao de informacao.',
      level: 7,
      weight: 60,
      groupId: 3,
      subGroupId: 2,
    },
    {
      id: 38,
      label: 'EPD001',
      title: 'ORGANIZAÇÃO INDUSTRIAL PARA ENGENHARIA',
      details: 'Empresas: administração e organização. Métodos de planejamento e controle. Administração financeira Administração de pessoal. Administração de suprimento. Contabilidade e balanço OBJETIVO: visão geral dos sistemas de produção em seus aspectos históricos (formas, evolução, tendência atuais) e sistemáticos (estruturas e componentes dos sistemas de produção, formas e modelos de organização do trabalho e do gerenciamento da produção), que permitam compreender como se organiza uma empresa (ou unidade fabril) e como melhorar a sua eficiência. ',
      level: 7,
      weight: 60,
      groupId: 5,
    },
    {
      id: 39,
      label: 'ELEXXC',
      title: 'INTRODUÇÃO À APRENDIZAGEM DE MÁQUINA',
      details: '1. O Problema do Aprendizado de Máquina. Classificação, Regressão e Agrupamento. Avaliação de Modelos. Dilema entre Polarização e Variância.   2. Tipologia de Dados. Análise Exploratória de Dados: Histogramas, Ramos e Folhas, Scatterplots, Matrizes de Scatterplot, Box-plots, Matrizes de Correlação. 3. Modelos de Regressão Linear: Regressão Simples, Múltipla e Logística.  4. Interpretabilidade dos Coeficientes Estimados. Métricas para Avaliação de Modelos de Regressão. Seleção de Modelos Lineares e Regularização: Subset Selection, Regressão Ridge e LASSO. 5. Métodos de Reamostragem: Validação Cruzada (Hold-Out, Leave-One-Out e K-Fold), Bootstrap. 6. Árvores de Regressão. Árvores de Classificação. Florestas Aleatórias. 7. Aprendizagem não-Supervisionada: Análise de Componentes Principais e Agrupamento (K-Médias e Hierárquico) 8. Aplicações.',
      level: 7,
      weight: 30,
      groupId: 4,
      subGroupId: 5,
    },
    {
      id: 40,
      label: 'ELE088',
      title: 'TEORIA DA DECISAO',
      details: 'Otimização multiobjetivo e conjuntos de Pareto. Modelagem de preferências. Modelagem do risco e decisão sob incerteza. Jogos e decisão minimax. Decisão bayesiana. Sistemas de suporte à decisão.',
      level: 7,
      weight: 30,
      groupId: 4,
      subGroupId: 2,
    },
    {
      id: 41,
      label: 'ELEXXF',
      title: 'LABORATORIO DE SISTEMAS  II',
      details: 'Modelos caixa-preta. Otimização e problemas inversos. Síntese de sistemas por otimização.',
      level: 7,
      weight: 60,
      groupId: 2,
      subGroupId: 2,
    },
    {
      id: 42,
      label: 'ELEXXG',
      title: 'LABORATORIO DE SISTEMAS  III',
      details: 'Desenvolvimento de um projeto envolvendo sistemas discretos.',
      level: 8,
      weight: 60,
      groupId: 2,
      subGroupId: 2,
    },
    {
      id: 43,
      label: 'DCC023',
      title: 'REDES DE COMPUTADORES',
      details: 'Conceitos de sistemas distribuídos, redes de computadores, protocolos e serviços de comunicação. Arquitetura de redes de computadores. Camadas inferiores do modelo de referência de ISO: física, enlace e redes. Redes locais, interligação de redes; especificação de protocolos.',
      level: 8,
      weight: 60,
      groupId: 4,
      subGroupId: 3,
    },
    {
      id: 44,
      label: 'ELE090',
      title: 'MODELAGEM E SIMULACAO DE SISTEMAS A EVENTOS DISCRETOS',
      details: 'Sistemas e modelos, linguagens e automata, redes de petri, modelostemporizados, controle supervisorio, aplicacoes em engenharia.',
      level: 9,
      weight: 60,
      groupId: 4,
      subGroupId: 4,
    },
    {
      id: 45,
      label: 'ELTXXA',
      title: 'FUNDAMENTOS DE ANÁLISE E CONTROLE DE SISTEMAS LINEARES',
      details: 'Sistemas de controle fundamentais e tecnologia de sistemas de controle. Sensores, atuadores, modelagem física de sistemas, projeto e implementação de controladores realimentados. Técnicas operacionais usadas para descrever, analisar e projetar sistemas lineares em tempo contínuo. Transformadas de Laplace. Resposta via funções de transferência. Estabilidade. Especificações de desempenho. Projeto de controladores via funções de transferência. Resposta em frequência. Não linearidades simples.',
      level: 9,
      weight: 60,
      groupId: 4,
      subGroupId: 6,
    },
    {
      id: 46,
      label: 'ELEXXH',
      title: 'LABORATÓRIO DE SISTEMAS IV',
      details: 'Verificação, Validação e Testes (precisa explorar mais)',
      level: 9,
      weight: 60,
      groupId: 2,
      subGroupId: 2,
    },
    {
      id: 47,
      label: 'ELEXXK',
      title: 'LABORATÓRIO DE GESTÃO DE SISTEMAS',
      details: 'Ferramentas e técnicas para a gestão ágil de negócios, produtos, serviços e projetos apoiado em canvas (Value Proposition Canvas, Business Model Canvas, Mapa de Empatia, Product Model Canvas, Lean Canvas, Roadmaps, Gerenciamento da Visão do Produto e do Projeto, Scrum, Design Sprint, Design Thinking). Principais ferramentas e técnicas para a gestão preditiva de projetos (visão geral do PMBOK: grupos de processos e áreas de conhecimento).',
      level: 9,
      weight: 60,
      groupId: 2,
      subGroupId: 3,
    },
    {
      id: 48,
      label: 'ELE087',
      title: 'PROJETO MULTIDISCIPLINAR',
      details: 'Integração e aplicação dos conceitos e praticas das disciplinas já cursadas em um projeto multidisciplinar desenvolvido em equipe. Identificação das bases cientificas e tecnológicas necessárias e planejamento da solução. Modelagem e analise de sistemas de engenharia envolvendo problemas multifísica utilizando programas comerciais e/ou de domínio publico. Aspectos associados ao desempenho, custo, ergonomia, manufaturabilidade, testabilidade, manutenabilidade, confiabilidade e ciclo de vida deverão ser levados em conta no projeto.',
      level: 10,
      weight: 60,
      groupId: 5,
      subGroupId: 1,
    },
    {
      id: 49,
      label: 'EEE018',
      title: 'TRABALHO DE CONCLUSAO DE CURSO I',
      details: 'Elaboração de um projeto completo de engenharia envolvendo etapas de estudo do problema, concepção, simulação e implementação. Elaboração e apresentação de documentação técnica preliminar.',
      level: 10,
      weight: 90,
      groupId: 5,
      subGroupId: 2,
    },
    {
      id: 50,
      label: 'EEE019',
      title: 'TRABALHO DE CONCLUSAO DE CURSO II',
      details: 'Finalização do projeto elaborado, no projeto final de curso I e apresentação de monografia. Defesa do trabalho perante banca examinadora.',
      level: 11,
      weight: 90,
      groupId: 5,
      subGroupId: 3,
    },
    {
      id: 51,
      label: 'EEE020',
      title: 'ESTAGIO SUPERVISIONADO EM ENGENHARIA DE SISTEMAS',
      details: 'Atividades de treinamento, supervisionadas por um docente do curso, na área de atuação profissional do engenheiro de sistemas.',
      level: 12,
      weight: 165,
      groupId: 5,
      subGroupId: 3,
    },
  ],
  edges: [
    {
      id: 1,
      from: 1,
      to: 7,
      label: 'MAT001 -> MAT039',
    },
    {
      id: 2,
      from: 2,
      to: 7,
      label: 'MAT038 -> MAT039',
    },
    {
      id: 3,
      from: 4,
      to: 8,
      label: 'DCC203 -> DCC204',
    },
    {
      id: 4,
      from: 6,
      to: 13,
      label: 'FIS065 -> FIS069',
    },
    {
      id: 5,
      from: 7,
      to: 13,
      label: 'MAT039 -> FIS069',
    },
    {
      id: 6,
      from: 7,
      to: 14,
      label: 'MAT039 -> MAT040',
    },
    {
      id: 7,
      from: 8,
      to: 15,
      label: 'DCC204 -> DCC205',
    },
    {
      id: 8,
      from: 10,
      to: 17,
      label: 'ELT124 -> ELT029',
    },
    {
      id: 9,
      from: 13,
      to: 18,
      label: 'FIS069 -> FIS086',
    },
    {
      id: 10,
      from: 6,
      to: 19,
      label: 'FIS065 -> FIS152',
    },
    {
      id: 11,
      from: 1,
      to: 19,
      label: 'MAT001 -> FIS152',
    },
    {
      id: 12,
      from: 7,
      to: 20,
      label: 'MAT039 -> MAT002',
    },
    {
      id: 13,
      from: 8,
      to: 21,
      label: 'DCC204 -> ELEXXA',
    },
    {
      id: 14,
      from: 16,
      to: 22,
      label: 'ELE064 -> ELE065',
    },
    {
      id: 15,
      from: 14,
      to: 22,
      label: 'MAT040 -> ELE065',
    },
    {
      id: 16,
      from: 14,
      to: 23,
      label: 'MAT040 -> ELE082',
    },
    {
      id: 17,
      from: 15,
      to: 25,
      label: 'DCC205 -> ELEXXB',
    },
    {
      id: 18,
      from: 36,
      to: 25,
      label: 'DCC111 -> ELEXXB',
    },
    {
      id: 19,
      from: 22,
      to: 26,
      label: 'ELE065 -> ELE156',
    },
    {
      id: 20,
      from: 22,
      to: 27,
      label: 'ELE065 -> ELT079',
    },
    {
      id: 21,
      from: 10,
      to: 28,
      label: 'ELT124 -> ELT123',
    },
    {
      id: 22,
      from: 19,
      to: 29,
      label: 'FIS152 -> ENGXXA',
    },
    {
      id: 23,
      from: 13,
      to: 29,
      label: 'FIS069 -> ENGXXA',
    },
    {
      id: 24,
      from: 14,
      to: 29,
      label: 'MAT040 -> ENGXXA',
    },
    {
      id: 25,
      from: 27,
      to: 30,
      label: 'ELT079 -> ELT080',
    },
    {
      id: 26,
      from: 12,
      to: 34,
      label: 'EST031 -> EEE017',
    },
    {
      id: 27,
      from: 14,
      to: 35,
      label: 'MAT040 -> ELE077',
    },
    {
      id: 28,
      from: 8,
      to: 37,
      label: 'DCC204 -> DCC011',
    },
    {
      id: 29,
      from: 32,
      to: 41,
      label: 'ELEXXE -> ELEXXF',
    },
    {
      id: 30,
      from: 44,
      to: 42,
      label: 'ELE090 -> ELEXXG',
    },
    {
      id: 31,
      from: 17,
      to: 42,
      label: 'ELT029 -> ELEXXG',
    },
    {
      id: 32,
      from: 28,
      to: 42,
      label: 'ELT123 -> ELEXXG',
    },
    {
      id: 33,
      from: 30,
      to: 42,
      label: 'ELT080 -> ELEXXG',
    },
    {
      id: 34,
      from: 8,
      to: 43,
      label: 'DCC204 -> DCC023',
    },
    {
      id: 35,
      from: 36,
      to: 44,
      label: 'DCC111 -> ELE090',
    },
    {
      id: 36,
      from: 7,
      to: 45,
      label: 'MAT039 -> ELTXXA',
    },
    {
      id: 37,
      from: 34,
      to: 46,
      label: 'EEE017 -> ELEXXH',
    },
    {
      id: 38,
      from: 42,
      to: 48,
      label: 'ELEXXG -> ELE087',
    },
    {
      id: 39,
      from: 49,
      to: 50,
      label: 'EEE018 -> EEE019',
    },
  ],
};

export default systemEngineerGraph;
